if (!require(remotes)) install.packages("remotes")
if (!require(OpenMx)) install.packages("Rccp")
if (!require(OpenMx)) install.packages("RccpEigen")
# if (!require(OpenMx)) install.packages("OpenMx")
remotes::install_deps()
if (!require(pkgload)) install.packages("pkgload")