help_text <- paste(
  "Command               Action",
  "--------------------------------------------------",
  "Right-Click           Right-Click Anywhere",
  "                      to get an Appropriate Menu",
  "o                     Create Observed Variable",
  "                      at Mouse Location",
  "l                     Create Latent Variable",
  "                      at Mouse Location",
  "c                     Create Constant Variable",
  "                      at Mouse Location",
  "Hold Space/X          Draw Directed Arrows",
  "                      by Connecting Variables With Mouse",
  "Hold ALT              Draw Undirected Arrows",
  "                      by Connecting Variables With Mouse",
  "Hold CTRL             Click on Multiple Elements to Select",
  "Hold CTRL             Click on Canvas to Activate Select Box",
  "Backspace             Remove Selected Elements",
  "CTRL+Z                Undo Some Diagram Changes",
  "CTRL+SHIFT+Z          Redo Some Diagram Changes",
  "",
  "Mac Users Replace CTRL with CMD, and ALT with OPTION",
  "",
  "",
  "Standard Workflow",
  "--------------------------------------------------",
  "1. Load your data (File --> Load Data)",
  "2. Draw your Model",
  "3. Check that autocomplete is correct (\"Autocompleted Model\")",
  "4. Fit Model (\"Estimates\")",
  sep = "\n"
)
